# permissions for end users to view elements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: element-viewer-role
rules:
- apiGroups:
  - client.matrix.bardiharborow.com
  resources:
  - elements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - client.matrix.bardiharborow.com
  resources:
  - elements/status
  verbs:
  - get
