# permissions for end users to edit elements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: element-editor-role
rules:
- apiGroups:
  - client.matrix.bardiharborow.com
  resources:
  - elements
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - client.matrix.bardiharborow.com
  resources:
  - elements/status
  verbs:
  - get
